name: CI-Test-2
on:
  push:
    branches: [ $default-branch ]
  workflow_dispatch:
    inputs:
      name:
        description: 'Your name'
        required: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Start eslint
        run: npm run lint
      - name: Run tests
        run: npm test
      - name: Check coverage
        run: npm run coverage
